# Generated by Django 5.1.4 on 2025-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='specifications',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
