# Generated by Django 5.1.4 on 2025-01-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_products_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['status'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='body',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='specifications',
            field=models.TextField(blank=True, max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствует'), ('sold_out', 'Распродано')], default='present', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
    ]
