# Generated by Django 5.1.4 on 2025-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_products_body_alter_products_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specifications',
            field=models.TextField(blank=True, max_length=750, verbose_name='Характеристики'),
        ),
    ]
