# Generated by Django 5.1.4 on 2025-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_products_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
