# Generated by Django 5.1.4 on 2025-01-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spec', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status', '-create'], name='mysite_prod_status_ce48d8_idx'),
        ),
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='mysite.products'),
        ),
    ]
