# Generated by Django 5.1.4 on 2025-01-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_specification_products_mysite_prod_status_ce48d8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='specifications',
        ),
    ]
