# Generated by Django 5.1.4 on 2025-01-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_products_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Название продукта')),
                ('body', models.TextField(verbose_name='Текст отзыва')),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Оценка')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания оценки')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления оценки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mysite.products', verbose_name='Продукт')),
            ],
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
