# Generated by Django 5.1.4 on 2025-01-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-mark', '-create'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
