# Generated by Django 5.1.4 on 2025-01-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания корзины')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления корзины')),
                ('counter', models.IntegerField(default=0, verbose_name='Колиечество товаров в корзине')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='mysite.products', verbose_name='Товары')),
            ],
            options={
                'ordering': ['-create'],
                'indexes': [models.Index(fields=['-create'], name='mysite_cart_create_7bc336_idx')],
            },
        ),
    ]
