# Generated by Django 5.1.4 on 2025-02-03 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='верификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный uuid верификации'),
        ),
    ]
